version: "3.8"
services:
    postgres:
        container_name: postgres_db
        image: postgres:15
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-playground_db}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - postgres_network
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - postgres_network
        restart: unless-stopped
        depends_on:
            - postgres

networks:
    postgres_network:
        driver: bridge

volumes:
    postgres_data:
    pgadmin_data:
